name: Flutter Matrix Build

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix: 
        include:
          - platform: ios
            os: macos-latest
            cmd: flutter build ios --no-codesign
          - platform: web
            os: ubuntu-latest
            cmd: flutter build web
          - platform: android
            os: ubuntu-latest
            cmd: flutter build apk --release

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses:  subosito/flutter-action@v2
        with: 
          channel: stable

      - name: Create key.properties
        if: matrix.platform == 'android'
        run: |
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties

      - name: Decode Keystore
        if: matrix.platform == 'android'
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

      - name: Build ${{ matrix.platform }}
        run: ${{ matrix.cmd }}