name: Flutter Matrix Build

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix: 
        include:

          - platform: web
            os: ubuntu-latest
            cmd: flutter build web
          - platform: android
            os: ubuntu-latest
            cmd: flutter build appbundle --release

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses:  subosito/flutter-action@v2
        with: 
          channel: stable

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

      - name: Decode keystore
        if: matrix.platform == 'android'
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > upload-keystore.jks
        
      - name: Build ${{ matrix.platform }}
        run: ${{ matrix.cmd }}
        env:
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          STORE_PATH: upload-keystore.jks 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/web


      