name: Flutter Matrix Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix: 
        include:
          - platform: web
            os: ubuntu-latest
            cmd: flutter build web
          - platform: android
            os: ubuntu-latest
            cmd: flutter build appbundle --release

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with: 
          channel: stable

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

      - name: Decode keystore
        if: matrix.platform == 'android'
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/upload-keystore.jks
        
      - name: Build ${{ matrix.platform }}
        run: ${{ matrix.cmd }}
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}          
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          STORE_FILE: upload-keystore.jks 
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/web

  deploy_android:
    name: Deploy Android to Play Store
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-android

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          # FIX 1: Change 'serviceAccountJsonRaw' to 'serviceAccountJsonPlainText'
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          
          # FIX 2: Point to the folder created by 'download-artifact@v4'
          releaseFiles: release-android/app-release.aab
          
          packageName: com.salih.cicdSample
          track: internal
          status: completed