name: Flutter Matrix Build

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix: 
        include:

          - platform: web
            os: ubuntu-latest
            cmd: flutter build web
          - platform: android
            os: ubuntu-latest
            cmd: flutter build appbundle --release

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses:  subosito/flutter-action@v2
        with: 
          channel: stable

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

      - name: Build ${{ matrix.platform }}
        run: ${{ matrix.cmd }}