name: Flutter Matrix Build

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix: 
        include:
          - platform: ios
            os: macos-latest
            cmd: flutter build ios --no-codesign
          - platform: web
            os: ubuntu-latest
            cmd: flutter build web
          - platform: android
            os: ubuntu-latest
            cmd: flutter build appbundle --release

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses:  subosito/flutter-action@v2
        with: 
          channel: stable

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

      # Decode Android secrets
      - name: Decode Android Keystore
        if: matrix.platform == 'android'
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks

      - name: Decode Android key.properties
        if: matrix.platform == 'android'
        env:
          ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
        run: |
          echo "$ANDROID_KEY_PROPERTIES" | base64 --decode > android/key.properties

      # Decode iOS secrets
      - name: Decode iOS GoogleService-Info.plist
        if: matrix.platform == 'ios'
        env:
          IOS_GOOGLE_SERVICE_INFO_PLIST_BASE64: ${{ secrets.IOS_GOOGLE_SERVICE_INFO_PLIST_BASE64 }}
        run: |
          echo "$IOS_GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Build ${{ matrix.platform }}
        run: ${{ matrix.cmd }}