name: Flutter Matrix Build

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix: 
        include:
          - platform: android
            os: ubuntu-latest
            command: flutter build apk --release
          - platform: web
            os: ubuntu-latest
            command: flutter build web

  runs-on: ${{ matrix.os }}

  steps:
    - uses: actions/checkout@v4
    - uses:  subosito/flutter-action@v2
      with: 
        channel: stable

    - run: flutter pub get

    - name: Build ${{ matrix.platform }}
      run: ${{ matrix.command }}